[project]
name = "DLC-Clarity-Smart-Contract-Redstone"

[[project.requirements]]
contract_id = "STDBEG5X8XD50SPM1JJH0E5CTXGDV5NJTJTTH7YB.redstone-verify"

[contracts.dlc-manager-pricefeed-v2-01]
path = "contracts/dlc-manager-pricefeed.clar"
depends_on = ["dlc-link-callback-trait"]

[contracts.dlc-link-callback-trait]
path = "contracts/dlc-link-callback-trait.clar"
depends_on = ["dlc-link-callback-trait"]

##### Development contracts:

[contracts.sample-protocol-contract]
path = "example/sample-protocol-contract.clar"
depends_on = ["dlc-manager-pricefeed-v2-01", "dlc-link-callback-trait"]

[contracts.callback-contract]
path = "tests/callback-contract-mock.clar"
depends_on = ["dlc-manager-pricefeed-v2-01"]
